- name: check fzf command exists
  command: fzf
  register: fzf_command_exists
  ignore_errors: true

- name: check fzf directory exists
  command: ls ~/.fzf
  register: fzf_directory_exists
  when: fzf_command_exists is failed
  ignore_errors: true

- name: download fzf
  shell: git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  when: fzf_directory_exists is failed and fzf_command_exists is failed

- name: install fzf
  shell: true | ~/.fzf/install --all
  when: fzf_command_exists is failed
