- name: Install neovim
  apt:
    name: neovim
    state: present
    update_cache: false
  become: true

- name: Install vim plugin prerequisites
  apt:
    name: "{{item}}"
    state: present
    update_cache: false
  loop:
    - exuberant-ctags
    - silversearcher-ag
  become: true
  ignore_errors: true

- name: Install ack-grep
  apt:
    name: ack-grep
    state: present
    update_cache: false
  become: true
  ignore_errors: true

- name: delete dotfiles.vim in home directory
  file:
    name: /home/{{username}}/dotfiles.vim
    state: absent

- name: trash dotfiles.vim if exists
  file:
    name: /home/{{username}}/.config/dotfiles.vim
    state: absent

- name: backup existing vim configuration
  shell: "mv ~/.{{item}} ~/.{{item}}.bak"
  loop:
    - vimrc
    - vim
  ignore_errors: true

- name: create temp directories
  file:
    dest: /home/{{username}}/.vim/.{{item}}
    state: directory
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0775
    recurse: true
  loop:
    - backup
    - swp
    - undo

- name: symlink config rc files
  file:
    src: /home/{{username}}/.config/dot/vim/{{item}}
    dest: /home/{{username}}/.{{item}}
    state: link
  loop:
    - vimrc

- name: symlink config directory
  file:
    src: /home/{{username}}/.config/dot/vim/config
    dest: /home/{{username}}/.vim/config
    state: link

- name: install vim-plug
  shell: "curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
